[workspace]
resolver = "2"

members = [
    "certval",
    "pkiprocmacros",
    "pittv3",
]

[profile.bench]
debug = true

[profile.release]
debug = true

[patch.crates-io]
x509-ocsp  = { git = "https://github.com/RustCrypto/formats.git" }
# FIXME: https://github.com/dalek-cryptography/curve25519-dalek/pull/676
ed25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek.git", branch = "rustcrypto-new-releases" }

[patch.'https://github.com/carl-wallace/pqckeys']
pqckeys = { git = "https://github.com/baloo/pqckeys.git", branch = "baloo/pre-releases" }
